import React, { Component } from 'react';

class Feed extends Component {
  render() {
    return (
      <div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
        <div>Feed</div>
      </div>
    );
  }
}

export default Feed;
