kind: pipeline
name: node:latest

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./.yarn-cache
      - ./node_modules
    volumes:
    - name: cache
      path: /tmp/cache:/cache

  - name: install
    image: node:latest
    commands:
    - node -v
    - npm -v
    - yarn --version
    - yarn config set cache-folder .yarn-cache
    - NODE_ENV=development yarn install --pure-lockfile

  - name: build
    image: node:latest
    environment:
      CONFIG:
        from_secret: DEVELOPMENT_CONFIG
    commands:
    - yarn client-build:dev
    - echo ${CONFIG} > config/development.json
    - ls -la config

  - name: publish
    image: plugins/docker
    repo: yukioru/akigami
    dockerfile: Dockerfile
    secrets:
      - source: docker_id
        target: docker_username
      - source: docker_password
        target: docker_password
    tags: [ latest, '${DRONE_TAG}' ]

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./.yarn-cache
      - ./node_modules
    volumes:
    - name: cache
      path: /tmp/cache:/cache